[package]
edition = "2021"
name = "ginger-ws"
version = "0.1.0"

[dependencies]
futures = "0.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1", features = ["full"]}
utoipa = {version = "2", features = ["json"]}
utoipa-swagger-ui = "2.0"
warp = "0.3"
