lang = "Rust"
organization_id = "ginger-society"
dir = "."
spec_url = "/notification/api-doc.json"
service_type = "RPCEndpoint"

[services."@ginger-society/IAMService"]
prod_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"
dev = "http://localhost:8080/iam"
stage_k8 = "http://iam-service-api-service/iam"
prod = "https://api.gingersociety.org/iam"

[portals_refs]

[ws_refs."@ginger-society/IAMService"]
prod = ""
stage_k8 = ""
dev = ""
stage = ""
prod_k8 = ""

[urls]
prod = "https://api.gingersociety.org"
stage = "https://api-staging.gingersociety.org"
dev = "http://localhost:3030"
stage_k8 = "http://notification-service-service"
prod_k8 = "http://notification-service-service"

[urls_ws]
stage_k8 = "ws://notification-service-service/notification"
prod_k8 = "ws://notification-service-service/notification"
prod = "wss://api.gingersociety.org/notification"
stage = "wss://api-staging.gingersociety.org/notification"
dev = "wss://api-staging.gingersociety.org/notification"
