lang = "Rust"
organization_id = "ginger-society"
dir = "."
spec_url = "/api-doc.json"
service_type = "RPCEndpoint"

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"

[portals_refs]

[urls]
prod = "http://localhost:3030"
prod_k8 = "http://localhost:3030"
stage_k8 = "http://notification-service/notification"
stage = "https://api-staging.gingersociety.org/notification"
dev = "http://localhost:3030/notification"
