dir = "."
lang = "Rust"
organization_id = "ginger-society"
service_type = "RPCEndpoint"
spec_url = "/notification/api-doc.json"

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs]

[urls]
dev = "http://localhost:3030"
prod = "http://localhost:3030"
prod_k8 = "http://localhost:3030"
stage = "https://api-staging.gingersociety.org"
stage_k8 = "http://notification-service-service"

[urls_ws]
dev = "wss://api-staging.gingersociety.org/notification" # for testing , use the staging env , for debugging use ws://localhost:3030/notification
prod = "wss://api.gingersociety.org/notification" 
prod_k8 = "ws://notification-service-service/notification" 
stage = "wss://api-staging.gingersociety.org/notification" 
stage_k8 = "ws://notification-service-service/notification"
